[package]
name = "rignalrar"
version = "0.1.0"
authors = ["Andrew Stanton-Nurse <andrew@andrewnurse.net>"]
edition = "2018"

[dependencies]
hyper = "0.13"
log = "0.4.5"
url = "1.7.1"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
futures-util = "0.3.1"
bytes = "0.5"