[package]
name = "sample_client"
version = "0.1.0"
authors = ["Andrew Stanton-Nurse <andrew@andrewnurse.net>"]
edition = "2018"

[dependencies]
rignalrar = { path = ".." }
url = "1.7.1"
futures = "0.3.1"
tokio = { version = "0.2.9", features = ["full"] }